require:
  - rubocop-rails
  - rubocop-performance
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.0
  Exclude:
    # You could specify set of files or dirs while you want to be ignored by rubocop
    - 'vendor/**/*'
    - 'bin/*'
    - 'db/schema.rb'
    - 'Gemfile.lock'
    - !ruby/regexp /old_and_unused\.rb$/
    - 'app/helpers/**/*'
    - 'config/environments/**/*'
    - 'app/jobs/**/*'
  NewCops: enable

Layout/LineLength:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/spec_helper.rb'
    - 'spec/**/*'

Metrics/MethodLength:
  Exclude:
    - 'app/controllers/graphql_controller.rb'
    - 'app/graphql/mutations/add_item_mutation.rb'

Naming/MethodParameterName:
  Exclude:
    - 'app/controllers/graphql_controller.rb'

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

Style/Documentation:
  Enabled: false
