default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: martian_library_development
  host: localhost
  username:
  password:

test:
  <<: *default
  database: martian_library_test
  host: localhost
  username: postgres
  password: postgres
